### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by reddec** [dceejay/node-red-contrib-zeromq#1]
Good day!

I want to create PR with some improvments. Before, I'll do it, I am glad to see your opinion/vision for this architecture questions:

* There are many types of sockets: PULL/PUSH, PUB/SUB and e.t.c. Have you any preference about how to choose type? (my vision - combo box)
* Maybe enough send only matched fields (mean with known fields names) in payload with special field for unknown arguments. Current implementation (modify node property as `part + i`  ) looks danger/unexpectly... I'm not sure. May be you have some reasons for that?
* As you know, `connect` or `bind` in ZMQ sockets can be applied for server AND client. May be just add some checkbox for this?

**Comment by dceejay** [comment]
Hi,
sure 
1) as long as they are supported by the underlying zeromq prebuilt package as-is then sure no problem... as long as the default is pub-sub as per now (non-breaking change), select box preferred I think... but yes please.
2) I wanted to be able to at least receive any parts of the message I didn't know about - otherwise how else would you discover them. If you have to specify them then you have to know about them in advance... so would prefer to leave as-is unless there are other ideas.
3) Sure - again as long as the default is as now - non-breaking change.

**Comment by reddec** [comment]
Thank you!
Maybe if you will have a moment, look at my old similiar project [node-red-contrib-zmq](https://github.com/reddec/node-red-contrib-zmq) I hope, that will show my vision.. Maybe will be a good idea to join our projects.

**Comment by dceejay** [comment]
Ah yes -hello !
maybe - but I'm not allowed to download GPL code... so I had to start clean on my own version.

**Comment by reddec** [comment]
MIT License will be OK?

**Comment by dceejay** [comment]
yes - just about anything but GPL/GPL3

**Comment by reddec** [comment]
Okay, I released new version (0.7.1) under MIT License.

**Comment by dceejay** [comment]
OK. Have some comments do you want them on your project instead of here ?
(Happy to try to blend them or adopt the best of both and keep separate :-)

**Comment by dceejay** [comment]
Added push pull modes, and ability to bind at either end to dc63bed7bc9d96ca16aafcb2f17941557d53c5f9
